int DC_Motor_Function(int PWM);
char Door_Feedback_Function(char Door_State);
void Door_Function();
char EStop_Function(char Operation_State);
char Keypad_Function(char Num_Pressed);
void LCD_Brightness(char Brightness_Level);
void LCD_Function();
void RGB_LED_Brightness(char Brightness_Level);
char RGB_LED_EN_DIS(char LED_State);
void Pin_Init();
